query allSolicitudPartidas{
  allSolicitudPartidas{
    edges{
      node{
        id
        tipo
        estado
        fechaInscripcion
        respuesta
        usuario{
          id
          nombre
          correo
          fechaNacimiento
        }
        
      }
    }
  }
}