mutation updateSolicitudPartida(
  $id: ID!
  $tipo: String!
  $estado: String!
  $respuesta:String!
  ){
  updateSolicitudPartida(
    partidaData:{
    id:$id
    tipo:$tipo
    estado:$estado
    respuesta:$respuesta
  }){
    partida{
      tipo
      estado
      respuesta
    }
  }
}