query allRegistroCurso{
  allRegistroCurso{
    edges{
      node{
        curso{
          nombreCurso
          id
        }
        usuario{
          nombre
          id
        }
      }
    }
  }
  
}