query allSolicitudes{
  allSolicitudes{
    edges{
      node{
        id
        estado
        hora
        fecha
        servicio{
          nombreServicio
        }
        usuario{
          id
          nombre
        }
        
      }
    }
  }
}